
name: master
on:
  push:
    branches:
      - master
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: tinvest-bot clone
      uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: test/coverage
      run: |
        sbt clean coverage test
        sbt coverageReport
    - name: sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -Dsonar.login=$SONAR_TOKEN sonarScan
